spring:
  datasource:
    host: localhost
    username: pamplona
    password: pamplona123
    port: 5432
    db: hostal_pamplona_db
    url: jdbc:postgresql://hostal-pamplona-db:5432/hostal_pamplona_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  activeProfileName: local

security:
  default:
    role: USER
  jwt:
    expiration-in-minutes: 120
